kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: codegen4-may5-1-imagestream-job-rolebinding
  namespace: redhat-ods-applications
subjects:
  - kind: ServiceAccount
    name: codegen4-may5-1-dsp-job
    namespace: codegen4-may5-1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: codegen4-may5-1-imagestream-job-role
